### ISSUE TITLE
Feedback: Thank you for making the courses available online and for free!

### ISSUE THREAD

**Issue by ghost** [earthlab-education/ea-bootcamp-day-12#3]
Hi!  
I am a petroleum geoscientist / microelectronics engineer who is benefiting tremendously from the Earth Analytics courses being online and for free and want to say thanks! It is the single most valuable piece of learning I am doing in 2018.  
Due to circumstances, I was looking for good free resources online and these courses have been perfect so far. It is written, so I can follow at my own pace, it is very guided and detailed, unlike some resources which are too "high-level", and it has an overarching theme in 2 fields I am passionate about.  
Wanted to let you guys know that you are making a difference for some people out there like me.  
Thanks!  
Scott

**Comment by jlpalomino** [comment]
@scottooi Thank you, Scott. We appreciate the feedback, and hope that you will find the other materials on our website useful as well, particularly the next series of lessons in the Earth Analytics Python course: https://www.earthdatascience.org/courses/earth-analytics-python/  Good luck in your process!
